name: writeFlag
on:
  push:
    tags:
        - 'v*'
    branches:
      - dev

jobs:
  writeFlag :
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          FLAG: ${{ github.ref }}
        run: |
          expr $FLAG \* 9 > latest.txt
      - name: Upload flag
        uses: actions/upload-artifact@v1
        with:
          name: flag
          path: flag/latest.txt
